### ISSUE TITLE
Request cancellation exception in RequestQueue#cancelAll method

### ISSUE THREAD

**Issue by afshin-hoseini** [afshin-hoseini/Netup#6]

**Comment by afshin-hoseini** [comment]
An exception sample for this bug:


```
java.lang.NullPointerException: Attempt to invoke virtual method 'void ir.afshin.netup.Requests.Request.cancel()' on a null object reference
                                                                 at ir.afshin.netup.Requests.RequestQueue.cancelAll(RequestQueue.java:344)
                                                                 at ir.afe.spot.Activities.TravelPanel.TravelControlPanel.Steps.TravelFlow_travelConfirmation.cancel(TravelFlow_travelConfirmation.java:110)
                                                                 at ir.afe.spot.Activities.TravelPanel.TravelControlPanel.Steps.TravelFlow_travelConfirmation.lambda$-ir_afe_spot_Activities_TravelPanel_TravelControlPanel_Steps_TravelFlow_travelConfirmation_lambda$4(TravelFlow_travelConfirmation.java:62)
                                                                 at ir.afe.spot.Activities.TravelPanel.TravelControlPanel.Steps.TravelFlow_travelConfirmation$$Lambda$-android_view_View_onCreateView_android_view_LayoutInflater_inflater_android_view_ViewGroup_container_android_os_Bundle_savedInstanceState_LambdaImpl0.onClick(Unknown Source)
                                                                 at android.view.View.performClick(View.java:5697)
                                                                 at android.widget.TextView.performClick(TextView.java:10815)
                                                                 at android.view.View$PerformClick.run(View.java:22534)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
